#! /bin/bash

#The game executeable File

TtyAttr="$(stty -g)"
GoOn=1
ProcArgs=( "$@" )

ExecuteAblePath="$(realpath "$0")"
ProcPos="${ExecuteAblePath%\/*}"

#Show Error
function serr {
	echo '[0;0H[5TTHE PROGRAM HAD A PROBLEM WITH RETURN VALUE '"$1"'!'
	stty "$TtyAttr"
	read -N 1
	. "$ProcPos"'/report.sh'
	exit "$1"
}

while [ "$GoOn" == 1 ];do
	GoOn=0
	GameRetVal=0
	. "$ProcPos"'/game.sh' -c "${ProcArgs[@]}";
	case "$GameRetVal" in
		0) exit ;;
		1) exit 2;;
		2) bash -t;;
		3) echo 'Open File,This will disable ALL ARGUMENTS when game start'
			unset ProcArgs
			read -re -i "$HOME"'/' ProcArgs[0]
			GoOn=1 ;;
		13) echo 'The game loaded fail because of empty $GameDir,just try to run this again';;
		*) serr "$GameRetVal";;
	esac
done
